name: Deploy

on:
  push:
    branches:
      - step2

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deleting forwarding rules
        run: |
          sudo iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 22
          sudo iptables -t nat -D PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 22
          sudo iptables -t nat -D PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 22
          sudo iptables -t nat -L PREROUTING -v -n

#      - name: Build with Gradle
#        run: ./gradlew bootJar
#
#      - name: Stop the services
#        run: sudo systemctl stop roomescape
#
#      - name: Copy runnable file
#        run: mkdir -p /home/ubuntu/${{ github.event.repository.name }} &&
#          cp build/libs/${{ github.event.repository.name }}-0.0.1-SNAPSHOT.jar
#          /home/ubuntu/${{ github.event.repository.name }}/run.jar
#
#      - name: Start the services
#        run: sudo systemctl start roomescape
