name: Deploy

on:
  push:
    branches:
      - step2

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Establish ssh reverse tunneling
        run: nohup sshpass -p 'YghHome1!' ssh -f -N -R 2222:localhost:22 root@ca.iptime.org

#      - name: Build with Gradle
#        run: ./gradlew bootJar
#
#      - name: Stop the services
#        run: sudo systemctl stop roomescape
#
#      - name: Copy runnable file
#        run: mkdir -p /home/ubuntu/${{ github.event.repository.name }} &&
#          cp build/libs/${{ github.event.repository.name }}-0.0.1-SNAPSHOT.jar
#          /home/ubuntu/${{ github.event.repository.name }}/run.jar
#
#      - name: Start the services
#        run: sudo systemctl start roomescape
